### ISSUE TITLE
Fails many tests in demerphq/smhasher

### ISSUE THREAD

**Issue by demerphq** [jbruchon/jodyhash#3]
I took the liberty of adding jody hash to my fork of Smhasher.

jodyhash32            32  32  32 FAILED 78 of 187 tests. Avalanche: 17-41, Cyclic: 43, 51-52, Differential: 9, 12, 15-16, Hi-Lo: 156-158, HiBit-Null: 150-152, Highbits2: 148-149, Highbits: 145-146, LowBit-Null: 153-155, Lowbits: 142-143, OverAll: 187, Sparse: 68, 70, 72, 74-80, Text: 159-162, 164-165, TwoBytes: 54-63, Words: 185, Zeroes: 167, 169-170
jodyhash64            64  64  64 FAILED 84 of 187 tests. Avalanche: 17-41, Differential: 12, 15-16, Effs: 181, 183-184, Hi-Lo: 156-158, HiBit-Null: 150-152, Highbits2: 148-149, Highbits: 144-146, LowBit-Null: 153-155, Lowbits: 141-143, OverAll: 187, Sanity: 4-5, Sparse: 65-67, 69, 71, 73-80, Text: 160-162, 164-165, TwoBytes: 54-63, Words: 186, Zeroes: 166-170

The avalanche tests in the old smhasher are pretty bad, and do not test the seed properly. You fail pretty much all of those tests in my version, along with a lot of other errors.

https://github.com/demerphq/smhasher/blob/master/doc/jodyhash32.32.32.32.txt
https://github.com/demerphq/smhasher/blob/master/doc/jodyhash64.64.64.64.txt

yves

**Comment by jbruchon** [comment]
I already added this to another SMHasher (there are so many forks of it that I already forgot which) and it already said that the algorithm isn't good. Thanks for the added confirmation.
